# Generated by Django 5.0 on 2023-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=50)),
                ('groom_name', models.CharField(max_length=50)),
                ('bride_age', models.IntegerField()),
                ('groom_age', models.IntegerField()),
                ('wedding_date', models.DateField(verbose_name='Wedding Date')),
                ('location', models.CharField(max_length=250)),
                ('guests', models.IntegerField()),
            ],
        ),
    ]
