# Generated by Django 5.0 on 2023-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='clients',
            field=models.ManyToManyField(to='main_app.client'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='area_of_expertise',
            field=models.CharField(choices=[('PP', 'PreWedding Photography'), ('PV', 'PreWedding Videography'), ('PB', 'PreWedding Photography & Videography'), ('WP', 'Wedding Photography'), ('WV', 'Wedding Videography'), ('WB', 'Wedding Photography & Videography')], default='PP', max_length=50),
        ),
    ]
