# Generated by Django 5.0 on 2023-12-19 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photographer_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='area_of_expertise',
            field=models.CharField(choices=[('PP', 'PreWedding Photography'), ('PV', 'PreWedding Videography'), ('PB', 'PreWedding Photography & Videography'), ('WP', 'Wedding Photography'), ('WV', 'Wedding Videography'), ('WB', 'Wedding Photography & Videography')], default='PP', max_length=2),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='main_app.photographer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='main_app.client')),
            ],
        ),
    ]
