# Generated by Django 5.0 on 2023-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_photographer_area_of_expertise_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='area_of_expertise',
            field=models.CharField(choices=[('WP', 'Wedding Photography'), ('WV', 'Wedding Videography'), ('WB', 'Wedding Photography & Videography'), ('PP', 'PreWedding Photography'), ('PV', 'PreWedding Videography'), ('PB', 'PreWedding Photography & Videography'), ('AL', 'All-round')], default='WP', max_length=2),
        ),
    ]
